---
title: "Class Practice 2"
author: "Mac"
date: "`r Sys.Date()`"
output:
  html_document:
    toc: TRUE
    toc_float: TRUE
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE,
                      message = FALSE,
                      warning = FALSE,
                      fig.path = "../Output/")
```

# Load libraries

```{r}
library(here)
library(tidyverse)
library(palmerpenguins)
library(kableExtra)
library(memer)
```

# Inspect the data

```{r}
glimpse(penguins)
```

# Make a plot

Plot the penguin data with bill length by bill depth.

```{r penguin, fig.asp=1.2, fig.align='center', fig.cap="This is my penguin figure.", dev="pdf", echo=FALSE}
penguins %>% # using the penguin dataset
  ggplot(aes(x = bill_length_mm,
             y = bill_depth_mm,
             color = species))+
  geom_point() +
  geom_smooth(method = "lm") + # Add a linear regression
  labs(x = "Bill Length (mm)",
       y = "Bill Depth (mm)",
       color = "Species") +
  theme_bw()
```

# Make a table

| Time  | Session | Topic    |
|:------|:-------:|---------:|
| _left_ | _center_| _right_ |
| 01:00  | 1       | Anatomy |
| 01:50  |         | *Break* |
| 02:00  | 2       | Tables  |
| 02:45  |         | *Break* |

# Make a table with kable

```{r}
penguins %>%
  group_by(species) %>%
  summarise(billmean = mean(bill_length_mm, na.rm = TRUE)) %>%
  kbl() %>% # make it a kable table
  kable_classic()%>%
  row_spec(2, bold = T, color = "white", background = "red") %>%
  kable_styling(full_width = FALSE)
```

# Totally awesome R package

```{r}
meme_get("DistractedBf") %>% 
  meme_text_distbf("Silly R package", "BIOL 551 students", "actual coding")

meme_get("DosEquisMan") %>% 
  meme_text_top("I don't always like coding", size = 28) %>% 
  meme_text_bottom("But when I do\nIt's always today's totally awesome R package", size = 18)
```

