---
title: "Week 12a - Iterative Coding"
author: "Mac"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries

```{r}
library(tidyverse)
library(here)
```

# Analyze Data

```{r}
print(paste("The year is", 2000))
```

```{r}
years<-c(2015:2021)
for (i in years){ # set up the for loop where i is the index
  print(paste("The year is", i)) # loop over i
}
```

```{r}
#Pre-allocate space for the for loop
# empty matrix
year_data<-data.frame(matrix(ncol = 2, nrow = length(years)))
# add column names
colnames(year_data)<-c("year", "year_name")
year_data
```

```{r}
for (i in 1:length(years)){ # set up the for loop where i is the index
  year_data$year_name[i]<-paste("The year is", years[i]) # loop over i
}
year_data
```

```{r}
for (i in 1:length(years)){ # set up the for loop where i is the index
  year_data$year_name[i]<-paste("The year is", years[i]) # loop over year name
  year_data$year[i]<-years[i] # loop over year
}
year_data
```

```{r}
testdata<-read_csv(here("Week_12", "Data", "cond_data","011521_CT316_1pcal.csv"))
glimpse(testdata)
```

```{r}
# point to the location on the computer of the folder
CondPath<-here("Week_12", "Data", "cond_data")
# list all the files in that path with a specific pattern
# In this case we are looking for everything that has a .csv in the filename
# you can use regex to be more specific if you are looking for certain patterns in filenames
files <- dir(path = CondPath,pattern = ".csv")
files
```

```{r}
# pre-allocate space
# make an empty dataframe that has one row for each file and 3 columns
cond_data<-data.frame(matrix(nrow = length(files), ncol = 3))
# give the dataframe column names
colnames(cond_data)<-c("filename","mean_temp", "mean_sal")
cond_data
```

```{r}
raw_data<-read_csv(paste0(CondPath,"/",files[1])) # test by reading in the first file and see if it works
head(raw_data)
```

```{r}
mean_temp<-mean(raw_data$Temperature, na.rm = TRUE) # calculate a mean
mean_temp
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files
}
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
glimpse(raw_data)
}
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
} 
cond_data
```

```{r}
for (i in 1:length(files)){ # loop over 1:3 the number of files 
raw_data<-read_csv(paste0(CondPath,"/",files[i]))
#glimpse(raw_data)
cond_data$filename[i]<-files[i]
cond_data$mean_temp[i]<-mean(raw_data$Temperature, na.rm =TRUE)
cond_data$mean_sal[i]<-mean(raw_data$Salinity, na.rm =TRUE)
} 
cond_data
```

```{r}
1:10 # a vector from 1 to 10 (we are going to do this 10 times)
```

```{r}
1:10 %>% # a vector from 1 to 10 (we are going to do this 10 times) %>% # the vector to iterate over
  map(rnorm, n = 15) # calculate 15 random numbers based on a normal distribution in a list
```

```{r}
1:10 %>% # a vector from 1 to 10 (we are going to do this 10 times) %>% # the vector to iterate over
  map(rnorm, n = 15)  %>% # calculate 15 random numbers based on a normal distribution in a list 
  map_dbl(mean) # calculate the mean. It is now a vector which is type "double"
```

```{r}
1:10 %>% # list 1:10
  map(function(x) rnorm(15, x)) %>% # make your own function
  map_dbl(mean)
```

```{r}
1:10 %>%
  map(~ rnorm(15, .x)) %>% # changes the arguments inside the function
  map_dbl(mean)
```

```{r}
# point to the location on the computer of the folder
CondPath<-here("Week_12", "Data", "cond_data")
files <- dir(path = CondPath,pattern = ".csv")
files
```

```{r}
files <- dir(path = CondPath,pattern = ".csv", full.names = TRUE)
#save the entire path name
files
```

```{r}
data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") # map everything to a dataframe and put the id in a column called filename
data
```

```{r}
data<-files %>%
  set_names()%>% # set's the id of each list to the file name
  map_df(read_csv,.id = "filename") %>% # map everything to a dataframe and put the id in a column called filename
  group_by(filename) %>%
  summarise(mean_temp = mean(Temperature, na.rm = TRUE),
            mean_sal = mean(Salinity,na.rm = TRUE))
data
```

```{r}
Sys.setenv(R_REMOTES_NO_ERRORS_FROM_WARNINGS="true")
## You might get a weird warning from this package about converting a warning to error.  This will get rid of that
remotes::install_github("jespermaag/gganatogram")
```

```{r}
library(gganatogram)
gganatogram(data = hgFemale_key, 
            organism = "human", sex = "female",
            fill = "colour", fillOutline = "#a6bddb") +
  theme_void() + 
  coord_fixed()
```

```{r}
hgMale_key %>%
  filter(type %in% "nervous_system") %>%
  gganatogram(organism = "human", sex = "male",
              fill = "colour", outline = FALSE) +
  theme_void() + 
  coord_fixed()
```

```{r}
gganatogram(data = mmFemale_key,
            organism = "mouse", sex = "female", 
            fillOutline = "#a6bddb", fill = "colour") +
  theme_void() +
  coord_fixed()
```

```{r}
gganatogram(data = cell_key$cell,
            organism = "cell",
            fillOutline = "#a6bddb", fill = "colour") +
  theme_void() +
  coord_fixed()
```

