---
title: "week_07_tue_map_homework"
author: "Mac"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, fig.path = "../Outputs/")
```

# Load Libraries

```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
library(ggdogs)
```

# Load Data

```{r}
meteorites <- readr::read_csv("https://raw.githubusercontent.com/rfordatascience/tidytuesday/master/data/2019/2019-06-11/meteorites.csv")
```

# Data Analysis

```{r worldwide_meteorites}

# World meteorite imacts

world<-map_data("world")

ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group),
               color = "black",
               fill = "palegreen4")+ # made landmasses pale green
  geom_point(data = meteorites,
             aes(x = long,
                 y = lat),
             alpha = 0.25,
             color = "maroon1") + # Maroon spots are meteorite impact sites
  theme(panel.background = element_rect(fill = "lightblue")) +
  coord_map(projection = "mercator",
            xlim = c(-180,180)) # can set limits of longitude (xlim) and latitude (ylim?) to zoom in
```