---
title: "week_07_tue_lecture"
author: "Mac"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Load Libraries

```{r}
library(tidyverse)
library(here)
library(maps)
library(mapdata)
library(mapproj)
library(ggdogs)
```

# Load Data

```{r}
# Read in data on population in California by county
popdata<-read_csv(here("Week_07","data","CApopdata.csv"))
#read in data on number of seastars at different field sites
stars<-read_csv(here("Week_07","data","stars.csv"))
```

# Data Analysis

```{r}
# get data for the entire world
world<-map_data("world")
head(world)

# get data for the USA
usa<-map_data("usa")
head(usa)

# get data for italy
italy<-map_data("italy")
head(italy)

# get data for states
states<-map_data("state")
head(states)

# get data for counties
counties<-map_data("county")
head(counties)

# group set to group
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat, group = group))

# group not set to group
ggplot()+
  geom_polygon(data = world, aes(x = long, y = lat))

# add color to the lines and fill
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, y = lat, group = group),
               color = "black")

ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group, 
                   fill = region),
               color = "black") +
  guides(fill = FALSE)

# Change fill
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat,
                   group = group,
                   fill = region),
               color = "black")+
  guides(fill = FALSE)+
  theme_minimal()

# Make the ocean blue
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group,
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))

# Use a mercator projection
ggplot()+
  geom_polygon(data = world, 
               aes(x = long, 
                   y = lat, 
                   group = group,
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "mercator",
            xlim = c(-180,180)) # can set limits of longitude (xlim) and latitude (ylim?) to zoom in

# Use a sinusoidal projection
ggplot()+
  geom_polygon(data = world, 
               aes(x = long,
                   y = lat,
                   group = group, 
                   fill = region),
               color = "black")+
  theme_minimal()+
  guides(fill = FALSE)+
  theme(panel.background = element_rect(fill = "lightblue"))+
  coord_map(projection = "sinusoidal",
            xlim = c(-180,180))
```

Map of just California

```{r}
# Use the states dataset
head(states)

# Use the states dataset
CA_data<-states %>%
  filter(region == "california") # filter out just the California data

# My attempt
ggplot()+
  geom_polygon(data = CA_data, 
               aes(x = long, y = lat, group = group),
               color = "black")

# Example from lecture slides
ggplot()+
geom_polygon(data = CA_data, 
             aes(x = long, 
                 y = lat, 
                 group = group), 
             color = "black")+
  coord_map()+
  theme_void()

# Plot the population of every county in California 

# First, we need to get the county level data and join it with our dataset on population (How do I do it?)

# Look at the county data
head(counties)[1:3,] # only showing the first 3 rows for space

# Look at the county data
head(popdata)

# Wrangle the data. Make the column names the same to join the two datasets.

CApop_county<-popdata %>%
  select("subregion" = County, Population)  %>% # rename the county col
  inner_join(counties) %>%
  filter(region == "california") # some counties have same names in other states

head(CApop_county)

# Map of CA population by county
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),
             color = "black")+
  coord_map()+
  theme_void()

# Make it log scale for easier interpretation.
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10") # can add color palette of your choice here

#Add a layer of points

#Look at the stars dataset. This has the number of seastars per/m2 at different sites in California.
head(stars)

# Map of CA population by county with seastars
# Add a geom_point layer.
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites
             aes(x = long,
                 y = lat))+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")

# Make points proportional to number of stars.
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")

# Make a better legend label.
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+ 
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")+
  labs(size = "# stars/m2")

# Save it.
ggplot()+
geom_polygon(data = CApop_county, 
             aes(x = long, 
                 y = lat, 
                 group = group,
                 fill = Population),  
             color = "black")+
  geom_point(data = stars, # add a point at all my sites 
             aes(x = long, 
                 y = lat,
                 size = star_no))+ 
  coord_map()+
  theme_void() +
  scale_fill_gradient(trans = "log10")+
  labs(size = "# stars/m2") 
  ggsave(here("Week_07","Outputs","CApop.pdf"))
```

```{r}
# Totally Awesome R package
ggplot(mtcars) +
  geom_dog(aes(mpg, wt), dog = "pug", size = 5)
```

